services:
  - type: web
    name: workflow-healer
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: 8000
    healthCheckPath: /health
